### PR TITLE
Feature fix o nonblock

### PR DESCRIPTION
**Pull request by everHannes**

### CODE REVIEW

**Comment by everHannes** [comment]
@a-krebs this branch seems to work ok for me
don't forget to compile with O_NONBLOCK set

first try on the initial connect however I've seen

```
Failed to verify SIG record
Invalid packet seqno: 2 != 1
Invalid packet seqno: 3 != 1
```

and it took a bit longer till it retried and uploaded a file that was added to the client offline

**Comment by gsliepen** [comment]
On Tue, Sep 06, 2016 at 04:06:32AM -0700, everHannes wrote:

> Assigned #35 to @gsliepen.

Ouch, redefining O_NONBLOCK? #if O_NONBLOCK is meant to test whether
this is set in the headers. It's better to unconditionally call
set_non_blocking() and have that function always use
ioctlsocket(FIONBIO) on Windows. Other than that, looks good. I can
merge it and add another commit to fix this.

## 

Met vriendelijke groet / with kind regards,
     Guus Sliepen guus@tinc-vpn.org

**Comment by everHannes** [comment]
> It's better to unconditionally call set_non_blocking() and have that function always use ioctlsocket(FIONBIO) on Windows.

isn't that what I do? see https://github.com/meshlink/meshlink/blob/3b591f398c0651e52932ff49b7d18c6412141b27/src/net_socket.c#L49

before it used non-blocking for windows when O_NONBLOCK was not set... _ouch_

**Comment by gsliepen** [comment]
On Tue, Sep 06, 2016 at 07:57:33AM -0700, everHannes wrote:

> > It's better to unconditionally call set_non_blocking() and have that function always use ioctlsocket(FIONBIO) on Windows.
> 
> isn't that what I do? see https://github.com/meshlink/meshlink/blob/3b591f398c0651e52932ff49b7d18c6412141b27/src/net_socket.c#L49

I was looking here:

https://github.com/meshlink/meshlink/blob/3b591f398c0651e52932ff49b7d18c6412141b27/src/net_socket.c#L74

The #ifdef O_NONBLOCK could go away here, and moved into the #else part
of set_non_blocking_socket(), right?

## 

Met vriendelijke groet / with kind regards,
     Guus Sliepen guus@tinc-vpn.org

**Comment by everHannes** [comment]
> The #ifdef O_NONBLOCK could go away here, and moved into the #else part of set_non_blocking_socket(), right?

oh, now I realize what you meant, the #ifdef O_NONBLOCK just checks whether the flag is available so the non blocking mode can be set
I thought it was meant to be a configuration option, am surprised there could be environments without

but yeah, move it and better log an error

**Comment by gsliepen** [comment]
On Tue, Sep 06, 2016 at 08:40:47AM -0700, everHannes wrote:

> > The #ifdef O_NONBLOCK could go away here, and moved into the #else part of set_non_blocking_socket(), right?
> 
> oh, now I realize what you meant, the #ifdef O_NONBLOCK just checks whether the flag is available so the non blocking mode can be set
> I thought it was meant to be a configuration option, am surprised there could be environments without
> 
> but yeah, move it and better log an error

Hm, it's an inheritance from tinc, which runs on a lot of OSes, and uh,
18 years ago things were at lot less standardized than now. I just
checked, it's only Windows which is holding out on O_NONBLOCK nowadays.

## 

Met vriendelijke groet / with kind regards,
     Guus Sliepen guus@tinc-vpn.org

**Comment by everHannes** [comment]
> Hm, it's an inheritance from tinc, which runs on a lot of OSes, and uh, 18 years ago things were at lot less standardized than now. I just checked, it's only Windows which is holding out on O_NONBLOCK nowadays.

that and given catta doesn't check for it either I removed the O_NONBLOCK check
in case it's missing I think it's better to have a compile error to be aware and address the issue anyway

**Pull request merged**
